# Generated by Django 2.0 on 2018-08-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=25)),
                ('player2', models.CharField(max_length=25)),
                ('block_counter_1', models.IntegerField(default=0)),
            ],
        ),
    ]
