# Generated by Django 2.0 on 2018-08-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='counter_2pt_player1',
            field=models.IntegerField(default=0),
        ),
    ]
