# Generated by Django 2.0 on 2018-08-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0004_auto_20180830_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='block_counter_1',
        ),
    ]
