# Generated by Django 2.0 on 2018-08-31 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0006_player_evaluator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
