# Generated by Django 2.0 on 2018-08-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0007_auto_20180831_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='evaluator',
        ),
    ]
