# Generated by Django 2.0 on 2018-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0008_remove_player_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='away_team',
            field=models.CharField(default='Away Team', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='home_team',
            field=models.CharField(default='Home Team', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='player1_jersey',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='player2_jersey',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='player3_jersey',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='player',
            name='player4_jersey',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='player',
            name='player5_jersey',
            field=models.IntegerField(default=5),
        ),
    ]
