# Generated by Django 2.0 on 2018-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0009_auto_20180831_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='home_team',
        ),
        migrations.AddField(
            model_name='player',
            name='awayteam',
            field=models.CharField(default='AT', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='hometeam',
            field=models.CharField(default='HT', max_length=30),
        ),
    ]
