# Generated by Django 2.0 on 2018-08-31 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0010_auto_20180831_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='awayteam',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hometeam',
        ),
    ]
