# Generated by Django 2.0 on 2018-09-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0011_auto_20180901_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player1_jersey',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player2_jersey',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player3_jersey',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player4_jersey',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player5_jersey',
        ),
    ]
