# Generated by Django 2.0 on 2018-09-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0013_auto_20180901_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='awayteam',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hometeam',
        ),
        migrations.AddField(
            model_name='player',
            name='away_team',
            field=models.TextField(default='away_team', max_length=25),
        ),
        migrations.AddField(
            model_name='player',
            name='home_team',
            field=models.TextField(default='home_team', max_length=25),
        ),
    ]
