# Generated by Django 2.0 on 2018-09-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0014_auto_20180901_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='away_team',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='home_team',
            field=models.TextField(),
        ),
    ]
