# Generated by Django 2.0 on 2018-09-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0015_auto_20180901_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='home_team',
        ),
    ]
