# Generated by Django 2.0 on 2018-09-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0016_auto_20180901_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player1_jersey',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='player2_jersey',
            field=models.CharField(default='02', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='player3_jersey',
            field=models.CharField(default='03', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='player4_jersey',
            field=models.CharField(default='04', max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='player5_jersey',
            field=models.CharField(default='05', max_length=2),
        ),
    ]
