# Generated by Django 2.0 on 2018-09-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0017_auto_20180901_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='away_team',
            field=models.CharField(default='Away Team', max_length=25),
        ),
        migrations.AddField(
            model_name='player',
            name='home_team',
            field=models.CharField(default='Home Team', max_length=25),
        ),
    ]
