# Generated by Django 2.0 on 2018-09-01 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Player', '0018_auto_20180901_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='evaluator',
            field=models.ForeignKey(default='Evaluator Random', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
