# Generated by Django 2.0 on 2018-09-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0019_player_evaluator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='evaluator',
        ),
    ]
